#!/usr/bin/env bash

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
cd /tmp
unzip awscliv2.zip
/tmp/aws/install -i $HOME/.local/opt/aws-cli -b $HOME/.local/bin

