flags: {}
extra-package-dbs: []
packages:
- .
- ./taffybar
# - location: ../../../../Projects/status-notifier-item
#   extra-dep: true
# - location: ../../../../Projects/gtk-sni-tray
#   extra-dep: true
extra-deps:
#- ../../dot.xmonad/xmonad
#- ../../dot.xmonad/xmonad-contrib
- rate-limit-1.4.3

resolver: nightly-2023-01-11
allow-newer: true
nix:
  packages:
    - cairo
    - gcc
    - gnome2.pango
    - gobjectIntrospection
    - gtk3
    - hicolor-icon-theme
    - libdbusmenu-glib
    - libdbusmenu-gtk3
    - libxml2
    - numix-icon-theme-circle
    - pkgconfig
    - x11
    - xorg.libX11
    - xorg.libXext
    - xorg.libXinerama
    - xorg.libXrandr
    - xorg.libXrender
    - zlib
