packages:
- '.'
- location: './taffybar'
  extra-dep: true
extra-deps:
- X11-xft-0.3.1
- alsa-core-0.5.0.1
- alsa-mixer-0.2.0.3
- dbus-1.0.1
- dbus-hslogger-0.1.0.1
- directory-1.3.2.2
- gi-dbusmenu-0.4.1
- gi-dbusmenugtk3-0.4.1
- gi-gdk-3.0.15
- gi-gdkpixbuf-2.0.16
- gi-gdkx11-3.0.2
- gi-gio-2.0.18
- gi-glib-2.0.17
- gi-gtk-3.0.21
- gi-gtk-hs-0.3.6.1
- gi-pango-1.0.16
- gi-xlib-2.0.2
- gtk-sni-tray-0.1.5.0
- gtk-strut-0.1.2.1
- gtk-traymanager-1.0.1
- gtk3-0.14.9
- haskell-gi-0.21.2
- haskell-gi-base-0.21.1
- http-types-0.12.1
- libxml-sax-0.7.5
- rate-limit-1.1.1
- status-notifier-item-0.3.0.0
- time-1.8.0.4
- time-units-1.0.0
- unix-2.7.2.2
- xml-helpers-1.0.0
- xmonad-contrib-0.13
resolver: lts-9.21
nix:
  packages:
    - cairo
    - gcc
    - gnome2.pango
    - gobjectIntrospection
    - gtk3
    - hicolor-icon-theme
    - libdbusmenu-glib
    - libdbusmenu-gtk3
    - libxml2
    - numix-icon-theme-circle
    - pkgconfig
    - x11
    - xorg.libX11
    - xorg.libXext
    - xorg.libXinerama
    - xorg.libXrandr
    - xorg.libXrender
    - zlib
