[tools]
java = "openjdk-17"
go = "1.26.2"
awscli = "latest"
aws-vault = "latest"
node = "latest"
ktlint = "latest"
krew = "latest"
bazelisk = "latest"
shfmt = "latest"
kustomize = "latest"
terraform = "latest"
yq = "latest"
conftest = "latest"
kubectl = "latest"
flux2 = "latest"
grpcurl = "latest"
cmctl = "latest"
pre-commit = "latest"
uv = "0.9.7"
helm = "latest"
shellcheck = "latest"
graalvm = "latest"
cue = "0.16.1"
python = "3.14.2"

[tools."http:amtool"]
version = "0.28.1"
url = "https://github.com/prometheus/alertmanager/releases/download/v{{version}}/alertmanager-{{version}}.linux-amd64.tar.gz"
bin_path = "alertmanager-{{version}}.linux-amd64"
