flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- ./xmonad
- ./xmonad-contrib

resolver: lts-16.17
nix:
  packages:
    - pkgconfig
    - x11
    - xorg.libX11
    - xorg.libXext
    - xorg.libXinerama
    - xorg.libXrandr
    - xorg.libXrender
    - xorg.libXScrnSaver
