[tools]
java = "openjdk-17"
go = "1.21"
awscli = "latest"
aws-vault = "latest"
node = "latest"
ktlint = "latest"
krew = "latest"
bazelisk = "latest"
shfmt = "latest"
kustomize = "latest"
terraform = "latest"
yq = "latest"
conftest = "latest"
kubectl = "latest"
